# Secure Logging Configuration

version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  json:
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    format: '%(asctime)s %(name)s %(levelname)s %(message)s'

filters:
  sensitive_data:
    (): conversation_analytics.utils.log_filters.SensitiveDataFilter
    patterns: ['password', 'token', 'api_key', 'secret']

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    filters: [sensitive_data]
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json
    filters: [sensitive_data]
    filename: logs/app.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: json
    filters: [sensitive_data]
    filename: logs/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

loggers:
  conversation_analytics:
    level: DEBUG
    handlers: [console, file, error_file]
    propagate: no

  # Third-party loggers
  ollama:
    level: WARNING
    handlers: [console, file]
    propagate: false

root:
  level: WARNING
  handlers: [console] 