version: '3.8'

services:
  claude-agent:
    image: ${DOCKER_HUB_USERNAME:-dockerhubusername}/conversation-analysis-claude:${VERSION:-latest}
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    restart: unless-stopped
    volumes:
      - ../../logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  gpt4-agent:
    image: ${DOCKER_HUB_USERNAME:-dockerhubusername}/conversation-analysis-gpt4:${VERSION:-latest}
    ports:
      - "8001:8000"
    environment:
      - PORT=8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    volumes:
      - ../../logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  # Uncomment to add a reverse proxy if needed
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - claude-agent
  #     - gpt4-agent 